name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        pip install --user awscli
        export PATH=$PATH:$HOME/.local/bin
      if: runner.os == 'Linux'
  
    - name: Find latest ZIP file
      run: |
        latest_zip=$(find . -type f -name '*.zip' | sort | tail -n 1)
        mv "$latest_zip" latest-lambda-code.zip
      if: github.ref == 'refs/heads/main'

    - name: Deploy Lambda
      run: |
        aws configure set region us-east-1
        aws lambda update-function-code --function-name lambda1 --zip-file fileb://latest-lambda-code.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
